spring:
  application:
    name: pos-carts
#  h2:
#    console:
#      enabled: true
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/sa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

