spring:
  application:
    name: pos-order
  main:
    allow-circular-references: false
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        output-order:
          destination: output-order
#          binder: local_rabbit
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123

server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
