spring:
  application:
    name: pos-delivery
  main:
    allow-circular-references: false
  cloud:
    function:
      definition: orderIdConsumer
    stream:
      function:
        bindings:
          orderIdConsumer-in-0: output-order
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest
#                password: guest
#server:
#  port: 10000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123